// Auto-generated. Do not edit!

// (in-package kw_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CarrotGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.func = null;
      this.path = null;
    }
    else {
      if (initObj.hasOwnProperty('func')) {
        this.func = initObj.func
      }
      else {
        this.func = 0;
      }
      if (initObj.hasOwnProperty('path')) {
        this.path = initObj.path
      }
      else {
        this.path = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CarrotGoal
    // Serialize message field [func]
    bufferOffset = _serializer.int8(obj.func, buffer, bufferOffset);
    // Serialize message field [path]
    bufferOffset = _serializer.int8(obj.path, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CarrotGoal
    let len;
    let data = new CarrotGoal(null);
    // Deserialize message field [func]
    data.func = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [path]
    data.path = _deserializer.int8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'kw_msgs/CarrotGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '863fc84fc39f4df288540e2439ded070';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # function
    int8 SAVE_WAYPOINT = 0
    int8 FOLLOW_WAYPOINT = 1
    
    # pth num
    int8 PATH_ONE = 1
    int8 PATH_TWO = 2
    int8 PATH_THREE = 3
    
    # action filed
    # Dfine the goal
    int8 func
    int8 path
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CarrotGoal(null);
    if (msg.func !== undefined) {
      resolved.func = msg.func;
    }
    else {
      resolved.func = 0
    }

    if (msg.path !== undefined) {
      resolved.path = msg.path;
    }
    else {
      resolved.path = 0
    }

    return resolved;
    }
};

// Constants for message
CarrotGoal.Constants = {
  SAVE_WAYPOINT: 0,
  FOLLOW_WAYPOINT: 1,
  PATH_ONE: 1,
  PATH_TWO: 2,
  PATH_THREE: 3,
}

module.exports = CarrotGoal;
