; Auto-generated. Do not edit!


(cl:in-package kw_msgs-msg)


;//! \htmlinclude CarrotActionGoal.msg.html

(cl:defclass <CarrotActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type kw_msgs-msg:CarrotGoal
    :initform (cl:make-instance 'kw_msgs-msg:CarrotGoal)))
)

(cl:defclass CarrotActionGoal (<CarrotActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CarrotActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CarrotActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kw_msgs-msg:<CarrotActionGoal> is deprecated: use kw_msgs-msg:CarrotActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <CarrotActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kw_msgs-msg:header-val is deprecated.  Use kw_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <CarrotActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kw_msgs-msg:goal_id-val is deprecated.  Use kw_msgs-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <CarrotActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kw_msgs-msg:goal-val is deprecated.  Use kw_msgs-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CarrotActionGoal>) ostream)
  "Serializes a message object of type '<CarrotActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CarrotActionGoal>) istream)
  "Deserializes a message object of type '<CarrotActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CarrotActionGoal>)))
  "Returns string type for a message object of type '<CarrotActionGoal>"
  "kw_msgs/CarrotActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CarrotActionGoal)))
  "Returns string type for a message object of type 'CarrotActionGoal"
  "kw_msgs/CarrotActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CarrotActionGoal>)))
  "Returns md5sum for a message object of type '<CarrotActionGoal>"
  "692f71656eab153d06a067d7160011ed")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CarrotActionGoal)))
  "Returns md5sum for a message object of type 'CarrotActionGoal"
  "692f71656eab153d06a067d7160011ed")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CarrotActionGoal>)))
  "Returns full string definition for message of type '<CarrotActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%CarrotGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: kw_msgs/CarrotGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# function~%int8 SAVE_WAYPOINT = 0~%int8 FOLLOW_WAYPOINT = 1~%~%# pth num~%int8 PATH_ONE = 1~%int8 PATH_TWO = 2~%int8 PATH_THREE = 3~%~%# action filed~%# Dfine the goal~%int8 func~%int8 path~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CarrotActionGoal)))
  "Returns full string definition for message of type 'CarrotActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%CarrotGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: kw_msgs/CarrotGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# function~%int8 SAVE_WAYPOINT = 0~%int8 FOLLOW_WAYPOINT = 1~%~%# pth num~%int8 PATH_ONE = 1~%int8 PATH_TWO = 2~%int8 PATH_THREE = 3~%~%# action filed~%# Dfine the goal~%int8 func~%int8 path~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CarrotActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CarrotActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CarrotActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
