; Auto-generated. Do not edit!


(cl:in-package kw_msgs-msg)


;//! \htmlinclude CarrotResult.msg.html

(cl:defclass <CarrotResult> (roslisp-msg-protocol:ros-message)
  ((total
    :reader total
    :initarg :total
    :type cl:integer
    :initform 0))
)

(cl:defclass CarrotResult (<CarrotResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CarrotResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CarrotResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kw_msgs-msg:<CarrotResult> is deprecated: use kw_msgs-msg:CarrotResult instead.")))

(cl:ensure-generic-function 'total-val :lambda-list '(m))
(cl:defmethod total-val ((m <CarrotResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kw_msgs-msg:total-val is deprecated.  Use kw_msgs-msg:total instead.")
  (total m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CarrotResult>) ostream)
  "Serializes a message object of type '<CarrotResult>"
  (cl:let* ((signed (cl:slot-value msg 'total)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CarrotResult>) istream)
  "Deserializes a message object of type '<CarrotResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'total) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CarrotResult>)))
  "Returns string type for a message object of type '<CarrotResult>"
  "kw_msgs/CarrotResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CarrotResult)))
  "Returns string type for a message object of type 'CarrotResult"
  "kw_msgs/CarrotResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CarrotResult>)))
  "Returns md5sum for a message object of type '<CarrotResult>"
  "f85682cd6d745599e9ac7a42c6855c71")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CarrotResult)))
  "Returns md5sum for a message object of type 'CarrotResult"
  "f85682cd6d745599e9ac7a42c6855c71")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CarrotResult>)))
  "Returns full string definition for message of type '<CarrotResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%int64 total ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CarrotResult)))
  "Returns full string definition for message of type 'CarrotResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%int64 total ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CarrotResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CarrotResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CarrotResult
    (cl:cons ':total (total msg))
))
