// Generated by gencpp from file kw_msgs/ButtonRequest.msg
// DO NOT EDIT!


#ifndef KW_MSGS_MESSAGE_BUTTONREQUEST_H
#define KW_MSGS_MESSAGE_BUTTONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kw_msgs
{
template <class ContainerAllocator>
struct ButtonRequest_
{
  typedef ButtonRequest_<ContainerAllocator> Type;

  ButtonRequest_()
    : btn()  {
    }
  ButtonRequest_(const ContainerAllocator& _alloc)
    : btn(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _btn_type;
  _btn_type btn;





  typedef boost::shared_ptr< ::kw_msgs::ButtonRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kw_msgs::ButtonRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ButtonRequest_

typedef ::kw_msgs::ButtonRequest_<std::allocator<void> > ButtonRequest;

typedef boost::shared_ptr< ::kw_msgs::ButtonRequest > ButtonRequestPtr;
typedef boost::shared_ptr< ::kw_msgs::ButtonRequest const> ButtonRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kw_msgs::ButtonRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kw_msgs::ButtonRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kw_msgs::ButtonRequest_<ContainerAllocator1> & lhs, const ::kw_msgs::ButtonRequest_<ContainerAllocator2> & rhs)
{
  return lhs.btn == rhs.btn;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kw_msgs::ButtonRequest_<ContainerAllocator1> & lhs, const ::kw_msgs::ButtonRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kw_msgs::ButtonRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kw_msgs::ButtonRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kw_msgs::ButtonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kw_msgs::ButtonRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kw_msgs::ButtonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kw_msgs::ButtonRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kw_msgs::ButtonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a39a9e07f6787f3ce35e3cfe1002e17f";
  }

  static const char* value(const ::kw_msgs::ButtonRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa39a9e07f6787f3cULL;
  static const uint64_t static_value2 = 0xe35e3cfe1002e17fULL;
};

template<class ContainerAllocator>
struct DataType< ::kw_msgs::ButtonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kw_msgs/ButtonRequest";
  }

  static const char* value(const ::kw_msgs::ButtonRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kw_msgs::ButtonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string btn\n"
;
  }

  static const char* value(const ::kw_msgs::ButtonRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kw_msgs::ButtonRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.btn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ButtonRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kw_msgs::ButtonRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kw_msgs::ButtonRequest_<ContainerAllocator>& v)
  {
    s << indent << "btn: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.btn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KW_MSGS_MESSAGE_BUTTONREQUEST_H
