// Generated by gencpp from file kw_msgs/ButtonResponse.msg
// DO NOT EDIT!


#ifndef KW_MSGS_MESSAGE_BUTTONRESPONSE_H
#define KW_MSGS_MESSAGE_BUTTONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kw_msgs
{
template <class ContainerAllocator>
struct ButtonResponse_
{
  typedef ButtonResponse_<ContainerAllocator> Type;

  ButtonResponse_()
    : flag(false)  {
    }
  ButtonResponse_(const ContainerAllocator& _alloc)
    : flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::kw_msgs::ButtonResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kw_msgs::ButtonResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ButtonResponse_

typedef ::kw_msgs::ButtonResponse_<std::allocator<void> > ButtonResponse;

typedef boost::shared_ptr< ::kw_msgs::ButtonResponse > ButtonResponsePtr;
typedef boost::shared_ptr< ::kw_msgs::ButtonResponse const> ButtonResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kw_msgs::ButtonResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kw_msgs::ButtonResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kw_msgs::ButtonResponse_<ContainerAllocator1> & lhs, const ::kw_msgs::ButtonResponse_<ContainerAllocator2> & rhs)
{
  return lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kw_msgs::ButtonResponse_<ContainerAllocator1> & lhs, const ::kw_msgs::ButtonResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kw_msgs::ButtonResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kw_msgs::ButtonResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kw_msgs::ButtonResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kw_msgs::ButtonResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kw_msgs::ButtonResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kw_msgs::ButtonResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kw_msgs::ButtonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24842bc754e0f5cc982338eca1269251";
  }

  static const char* value(const ::kw_msgs::ButtonResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24842bc754e0f5ccULL;
  static const uint64_t static_value2 = 0x982338eca1269251ULL;
};

template<class ContainerAllocator>
struct DataType< ::kw_msgs::ButtonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kw_msgs/ButtonResponse";
  }

  static const char* value(const ::kw_msgs::ButtonResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kw_msgs::ButtonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool flag\n"
;
  }

  static const char* value(const ::kw_msgs::ButtonResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kw_msgs::ButtonResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ButtonResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kw_msgs::ButtonResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kw_msgs::ButtonResponse_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KW_MSGS_MESSAGE_BUTTONRESPONSE_H
