// Generated by gencpp from file kw_msgs/CarrotResult.msg
// DO NOT EDIT!


#ifndef KW_MSGS_MESSAGE_CARROTRESULT_H
#define KW_MSGS_MESSAGE_CARROTRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kw_msgs
{
template <class ContainerAllocator>
struct CarrotResult_
{
  typedef CarrotResult_<ContainerAllocator> Type;

  CarrotResult_()
    : total(0)  {
    }
  CarrotResult_(const ContainerAllocator& _alloc)
    : total(0)  {
  (void)_alloc;
    }



   typedef int64_t _total_type;
  _total_type total;





  typedef boost::shared_ptr< ::kw_msgs::CarrotResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kw_msgs::CarrotResult_<ContainerAllocator> const> ConstPtr;

}; // struct CarrotResult_

typedef ::kw_msgs::CarrotResult_<std::allocator<void> > CarrotResult;

typedef boost::shared_ptr< ::kw_msgs::CarrotResult > CarrotResultPtr;
typedef boost::shared_ptr< ::kw_msgs::CarrotResult const> CarrotResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kw_msgs::CarrotResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kw_msgs::CarrotResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kw_msgs::CarrotResult_<ContainerAllocator1> & lhs, const ::kw_msgs::CarrotResult_<ContainerAllocator2> & rhs)
{
  return lhs.total == rhs.total;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kw_msgs::CarrotResult_<ContainerAllocator1> & lhs, const ::kw_msgs::CarrotResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kw_msgs::CarrotResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kw_msgs::CarrotResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kw_msgs::CarrotResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kw_msgs::CarrotResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kw_msgs::CarrotResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kw_msgs::CarrotResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kw_msgs::CarrotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f85682cd6d745599e9ac7a42c6855c71";
  }

  static const char* value(const ::kw_msgs::CarrotResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf85682cd6d745599ULL;
  static const uint64_t static_value2 = 0xe9ac7a42c6855c71ULL;
};

template<class ContainerAllocator>
struct DataType< ::kw_msgs::CarrotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kw_msgs/CarrotResult";
  }

  static const char* value(const ::kw_msgs::CarrotResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kw_msgs::CarrotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"int64 total \n"
;
  }

  static const char* value(const ::kw_msgs::CarrotResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kw_msgs::CarrotResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarrotResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kw_msgs::CarrotResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kw_msgs::CarrotResult_<ContainerAllocator>& v)
  {
    s << indent << "total: ";
    Printer<int64_t>::stream(s, indent + "  ", v.total);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KW_MSGS_MESSAGE_CARROTRESULT_H
