name: Cpp

on:
  push:
  pull_request:
    branches: 
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y build-essential cmake libasio-dev
    - name: Build and pack
      run: mkdir build && cd build && cmake -DBUILD_TESTS=ON .. && cmake --build . && cpack    
