# function
int8 SAVE_WAYPOINT = 0
int8 FOLLOW_WAYPOINT = 1

# pth num
int8 PATH_ONE = 1
int8 PATH_TWO = 2
int8 PATH_THREE = 3

# action filed
# Dfine the goal
int8 func
int8 path
---
# Define the result
int64 total 
---
# Define the feedback
int64 remaining
int64 current